
version: "3.9"

services:
  database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
    image: postgres
    container_name: database_dtserver
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=dtserver
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=dtmoney
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: dtserver
    ports: 
      - 2000:2000
      - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    volumes: 
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local